version: "3.1"

services:
  python:
    build: .
    restart: unless-stopped
    volumes:
     - ./telegram-rss-bot:/home/user/app
    command: python -u /home/user/app/telegram-rss-bot.py --interval 60
